[build]
  base = "/"
  command = "# no build command"
  publish = "frontend"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9.18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
