[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  functions = "netlify/functions"
  publish = "frontend"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
